---
- name: Add docker gpg key
  apt_key:
    data: "{{ lookup('file', 'files/docker.gpg') }}"
    state: present
- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker
    update_cache: yes
- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  register: result
  until: result is succeeded
  retries: 3
  delay: 10
- name: Enable docker to start on boot
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - docker
    - containerd
- name: Add docker bash completion
  copy:
    src: files/docker.bash-completion
    dest: /etc/bash_completion.d/docker
    mode: 0644