---
- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded
  retries: 3
  delay: 10